name: CI-Windows

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: windows-2019
    
    steps:
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - uses: actions/checkout@master
    - name: Build
      run: |
        dotnet publish /p:PublishProfile="Win64"
        cd .\bin\Release\net6.0\publish\win64
        7z a -tzip ReleaseWin64.zip *
        mkdir Source
        xcopy .\..\..\..\..\..\Documentation\Source\* .\Source /Y /E
        xcopy .\..\..\..\..\..\Documentation\CustomTemplate\* .\Templates /Y /E
        .\Generator.exe
        xcopy .\Output\* .\..\..\..\..\..\docs /Y /E
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: Release
        path: bin\Release\net6.0\publish\win64\ReleaseWin64.zip
    - name: Upload Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin\Release\net6.0\publish\win64\ReleaseWin64.zip
        asset_name: ReleaseWin64.zip
        tag: ${{ github.ref }}
        overwrite: true
    - name: Update Demo Page
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHubBot
        author_email: github@github.com
        message: Updated static files!
        github-token: ${{ secrets.GITHUB_TOKEN }}
